package org.woehlke.tools.config;

public interface QueueNames {

    String LOGBUCH_QUEUE = "LOGBUCH_QUEUE";
    String LOGBUCH_REPLY_QUEUE = "LOGBUCH_REPLY_QUEUE";

    String RENAME_FILES_QUEUE = "RENAME_FILES_QUEUE";
    String RENAME_FILES_QUEUE_REPLY = "RENAME_FILES_QUEUE_REPLY";

    String SCALE_IMAGES_QUEUE = "SCALE_IMAGES_QUEUE";
    String SCALE_IMAGES_QUEUE_REPLAY = "SCALE_IMAGES_QUEUE_REPLAY";

}
