package org.woehlke.tools.config;

public interface QueueNames {

    String JOB_RENAME_DIRECTORIES_QUEUE = "JOB_RENAME_DIRECTORIES_QUEUE";
    String JOB_RENAME_FILES_QUEUE = "JOB_RENAME_FILES_QUEUE";
    String JOB_RESIZE_IMAGES_QUEUE = "JOB_RESIZE_IMAGES_QUEUE";
    String JOB_IMAGES_INFO_JPG_QUEUE = "JOB_IMAGES_INFO_JPG_QUEUE";
    String JOB_IMAGES_INFO_PNG_QUEUE = "JOB_IMAGES_INFO_PNG_QUEUE";
    String LOGBUCH_QUEUE = "LOGBUCH_QUEUE";

    String JOB_RENAME_DIRECTORIES_QUEUE_REPLAY = "JOB_RENAME_DIRECTORIES_QUEUE_REPLAY";
    String JOB_RENAME_FILES_QUEUE_REPLAY = "JOB_RENAME_FILES_QUEUE_REPLAY";
    String JOB_RESIZE_IMAGES_QUEUE_REPLAY = "JOB_RESIZE_IMAGES_QUEUE_REPLAY";
    String JOB_IMAGES_INFO_JPG_QUEUE_REPLAY = "JOB_IMAGES_INFO_JPG_QUEUE_REPLAY";
    String JOB_IMAGES_INFO_PNG_QUEUE_REPLAY = "JOB_IMAGES_INFO_PNG_QUEUE_REPLAY";
    String LOGBUCH_QUEUE_REPLAY = "LOGBUCH_QUEUE_REPLAY";
}
