package org.woehlke.tools.config.properties;

public interface QueueNames {

    String JOB_RENAME_FILES_QUEUE = "JOB_RENAME_FILES_QUEUE";
    String JOB_IMAGES_RESIZE_QUEUE = "JOB_IMAGES_RESIZE_QUEUE";
    String JOB_IMAGES_INFO_QUEUE = "JOB_IMAGES_INFO_QUEUE";
    String LOGBUCH_QUEUE = "LOGBUCH_QUEUE";

    String JOB_RENAME_FILES_QUEUE_REPLY = "JOB_RENAME_FILES_QUEUE_REPLY";
    String JOB_IMAGES_RESIZE_QUEUE_REPLY = "JOB_IMAGES_RESIZE_QUEUE_REPLY";
    String JOB_IMAGES_INFO_QUEUE_REPLY = "JOB_IMAGES_INFO_QUEUE_REPLY";
    String LOGBUCH_QUEUE_REPLY = "LOGBUCH_QUEUE_REPLY";
}
